column_width = 30
line_endings = "Unix"
indent_type = "Tabs"
indent_width = 4
collapse_simple_statement = "Never"
quote_style = "ForceSingle"
#call_parentheses = "None"
block_newline_gaps = "Never"
call_parentheses = "None"
